test

diff --git a/.github/actions/image-scan/action.yml b/.github/actions/image-scan/action.yml
--- a/.github/actions/image-scan/action.yml
+++ b/.github/actions/image-scan/action.yml
@@ -53,7 +53,8 @@ runs:
         cat trivy-results.txt | tee -a $GITHUB_STEP_SUMMARY
 
     - name: Set image name
-      if: github.event_name == 'schedule' && failure()
+      # if: github.event_name == 'schedule' && failure()
+      if: failure()
       shell: bash
       run: |
         if [ -n "${{ inputs.image-name }}" ]; then
@@ -64,7 +65,8 @@ runs:
         echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
 
     - name: Create issue
-      if: github.event_name == 'schedule' && failure()
+      # if: github.event_name == 'schedule' && failure()
+      if: failure()
       shell: bash
       run: |
         ISSUE_NUM=`gh issue list --search "${{ env.IMAGE_NAME }} in:title sort:updated-desc" --state open --limit 1 --label image-vulnerability --json number --jq ".[].number"`
@@ -88,15 +90,53 @@ runs:
       env:
         GITHUB_TOKEN: ${{ inputs.github-token }}
 
-    - name: Send Slack notification
-      if: github.event_name == 'schedule' && failure()
-      id: slack
-      uses: slackapi/slack-github-action@v1.23
+    - name: Set create pull request flg
+      run: |
+        git branch -r | grep develop/fix-image-vulnerability
+        if [ $? -ne 0 ]; then
+          echo "SHOULD_CREATE_PR=true" >> $GITHUB_ENV 
+        fi
+
+    - name: Create Branch
+      if: ${{ env.SHOULD_CREATE_PR == 'true' }}
+      run: |
+        git add .
+        git commit -m "Update aws provider to ${LATEST_PROVIDER_VERSION}"
+        git push --set-upstream origin develop/fix-image-vulnerability
+        
+        DEFAULT_BRANCH=`git remote show origin | awk '/HEAD/ {print $NF}'`
+        echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV 
+
+    - name: Create pull request
+      if: ${{ env.SHOULD_CREATE_PR == 'true' }}
+      id: create-pr
+      uses: repo-sync/pull-request@master
       with:
-        payload: |
-          {
-              "text": ":warning: コンテナイメージ ${{ env.IMAGE_NAME }} に脆弱性が見つかりました ${{ env.ISSUE_URL }}"
-          }
-      env:
-        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-        SLACK_WEBHOOK_URL: ${{ inputs.slack-incoming-webhook-url }}
+        destination_branch: ${{ env.DEFAULT_BRANCH }}
+        source_branch: "develop/fix-image-vulnerability"
+        github_token: ${{ inputs.github-token }}
+        pr_title: コンテナイメージの脆弱性修正
+        pr_body: |
+          ## 概要
+          コンテナイメージの脆弱性修正
+  
+          ## 関連Issue
+          Fix ${{ env.ISSUE_URL }} 
+
+    - name: slack test
+      run: |
+        echo "コンテナイメージ ${{ env.IMAGE_NAME }} に脆弱性が見つかりました。対応をお願いします\n${{ steps.open-pr.outputs.pr_url }}"
+        echo "---------"
+
+#    - name: Send Slack notification
+#      if: github.event_name == 'schedule' && failure()
+#      id: slack
+#      uses: slackapi/slack-github-action@v1.23
+#      with:
+#        payload: |
+#          {
+#              "text": ":warning: コンテナイメージ ${{ env.IMAGE_NAME }} に脆弱性が見つかりました。対応をお願いします\n${{ steps.open-pr.outputs.pr_url }}"
+#          }
+#      env:
+#        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+#        SLACK_WEBHOOK_URL: ${{ inputs.slack-incoming-webhook-url }}
